### ISSUE TITLE
How to bootstrap it ? thanks

### ISSUE THREAD

**Issue by yanlee26** [stramel/eslint-plugin-polymer#5]

**Comment by stramel** [comment]
@yanlee26 Not entirely sure what you mean by that...

**Comment by yanlee26** [comment]
Thanks @stramel , and I wonder how to use it? I applied build tool of gulp, and installed the `eslint-plugin-polymer` , but I don't know whether it worked or not?

**Comment by stramel** [comment]
You must ensure whatever eslint file your gulp process is using has it declared in the plugins section. Read through the `gulp-eslint` and `eslint` documentation. This is just a plugin for eslint.
